// Code generated by mockery v2.0.0-alpha.2. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
	staff "github.com/touchtechnologies-product/go-blueprint-clean-architecture/service/staff"
	util "github.com/touchtechnologies-product/go-blueprint-clean-architecture/service/util"
)

// Service is an autogenerated mock type for the Service type
type Service struct {
	mock.Mock
}

// Create provides a mock function with given fields: ctx, input
func (_m *Service) Create(ctx context.Context, input *staff.CreateInput) (string, error) {
	ret := _m.Called(ctx, input)

	var r0 string
	if rf, ok := ret.Get(0).(func(context.Context, *staff.CreateInput) string); ok {
		r0 = rf(ctx, input)
	} else {
		r0 = ret.Get(0).(string)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *staff.CreateInput) error); ok {
		r1 = rf(ctx, input)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Delete provides a mock function with given fields: ctx, ID
func (_m *Service) Delete(ctx context.Context, ID string) error {
	ret := _m.Called(ctx, ID)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, ID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// List provides a mock function with given fields: ctx, opt
func (_m *Service) List(ctx context.Context, opt *util.PageOption) (int, []*staff.View, error) {
	ret := _m.Called(ctx, opt)

	var r0 int
	if rf, ok := ret.Get(0).(func(context.Context, *util.PageOption) int); ok {
		r0 = rf(ctx, opt)
	} else {
		r0 = ret.Get(0).(int)
	}

	var r1 []*staff.View
	if rf, ok := ret.Get(1).(func(context.Context, *util.PageOption) []*staff.View); ok {
		r1 = rf(ctx, opt)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).([]*staff.View)
		}
	}

	var r2 error
	if rf, ok := ret.Get(2).(func(context.Context, *util.PageOption) error); ok {
		r2 = rf(ctx, opt)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// Read provides a mock function with given fields: ctx, ID
func (_m *Service) Read(ctx context.Context, ID string) (*staff.View, error) {
	ret := _m.Called(ctx, ID)

	var r0 *staff.View
	if rf, ok := ret.Get(0).(func(context.Context, string) *staff.View); ok {
		r0 = rf(ctx, ID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*staff.View)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, ID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Update provides a mock function with given fields: ctx, ID, input
func (_m *Service) Update(ctx context.Context, ID string, input *staff.CreateInput) error {
	ret := _m.Called(ctx, ID, input)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, *staff.CreateInput) error); ok {
		r0 = rf(ctx, ID, input)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
