definitions:
  staff.View:
    properties:
      companyId:
        type: string
      createdAt:
        type: integer
      name:
        type: string
      tel:
        type: string
      updatedAt:
        type: integer
    type: object
info:
  contact: {}
  license: {}
paths:
  /staffsByCompany/{}:
    get:
      consumes:
      - application/json
      description: Get all the existing Staff
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/staff.View'
            type: array
      summary: List Staff By Company
swagger: "2.0"
